// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"omega/domain/base/basapi"
	"omega/domain/base/basrepo"
	"omega/domain/cafe/cafapi"
	"omega/domain/cafe/cafrepo"
	"omega/domain/html/htmapi"
	"omega/domain/service"
	"omega/internal/core"
)

// Injectors from wire.go:

func initSettingAPI(e *core.Engine) basapi.SettingAPI {
	settingRepo := basrepo.ProvideSettingRepo(e)
	basSettingServ := service.ProvideBasSettingService(settingRepo)
	settingAPI := basapi.ProvideSettingAPI(basSettingServ)
	return settingAPI
}

func initRoleAPI(e *core.Engine) basapi.RoleAPI {
	roleRepo := basrepo.ProvideRoleRepo(e)
	basRoleServ := service.ProvideBasRoleService(roleRepo)
	roleAPI := basapi.ProvideRoleAPI(basRoleServ)
	return roleAPI
}

func initUserAPI(engine *core.Engine) basapi.UserAPI {
	userRepo := basrepo.ProvideUserRepo(engine)
	basUserServ := service.ProvideBasUserService(userRepo)
	userAPI := basapi.ProvideUserAPI(basUserServ)
	return userAPI
}

func initAuthAPI(e *core.Engine) basapi.AuthAPI {
	basAuthServ := service.ProvideBasAuthService(e)
	authAPI := basapi.ProvideAuthAPI(basAuthServ)
	return authAPI
}

func initActivityAPI(engine *core.Engine) basapi.ActivityAPI {
	activityRepo := basrepo.ProvideActivityRepo(engine)
	basActivityServ := service.ProvideBasActivityService(activityRepo)
	activityAPI := basapi.ProvideActivityAPI(basActivityServ)
	return activityAPI
}

func initErrDescAPI(e *core.Engine) htmapi.ErrDescAPI {
	errDescAPI := htmapi.GenErrDescAPI(e)
	return errDescAPI
}

func initFoodAPI(e *core.Engine) cafapi.FoodAPI {
	foodRepo := cafrepo.ProvideFoodRepo(e)
	basFoodServ := service.ProvideBasFoodService(foodRepo)
	foodAPI := cafapi.ProvideFoodAPI(basFoodServ)
	return foodAPI
}

func initOrderAPI(e *core.Engine) cafapi.OrderAPI {
	orderRepo := cafrepo.ProvideOrderRepo(e)
	basOrderServ := service.ProvideBasOrderService(orderRepo)
	orderAPI := cafapi.ProvideOrderAPI(basOrderServ)
	return orderAPI
}

func initOrderFoodAPI(e *core.Engine) cafapi.OrderFoodAPI {
	orderFoodRepo := cafrepo.ProvideOrderFoodRepo(e)
	basOrderFoodServ := service.ProvideBasOrderFoodService(orderFoodRepo)
	orderFoodAPI := cafapi.ProvideOrderFoodAPI(basOrderFoodServ)
	return orderFoodAPI
}
